app/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^login/$', views.login_view, name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^$', views.Landing.as_view(), name='landing'),
    url(r'^signup/$', views.signup_view, name='signup'),
    url(r'^userprofile/$', views.UserProfile.as_view(success_url="/friend-finder/userprofile/"), name='userprofile'),
    url(r'^friends/$', views.add_friend_view, name='friends'),
    url(r'^connect/(?P<operation>.+)/(?P<pk>\d+)/$', views.manage_friend_request, name='manage_friend_requests')
]

friend_finder/urls.py
from django.conf.urls import url, include
from django.contrib.gis import admin
from rest_framework.authtoken import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^api-token-auth/', views.obtain_auth_token),
    url('friend-finder/', include('app.urls', namespace="app")),
    url(r'^api/', include('app.rest_urls', namespace="api")),
    url(r'^friendship/', include('friendship.urls'))
]

templates/app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Friend Finder</title>

    {% load leaflet_tags %}
    {% load static %}

    {% leaflet_js plugins="forms" %}
    {% leaflet_css plugins="forms" %}

{#    <link rel="shortcut icon" href="{% static "Users/images/favicon.ico" %}" type="image/x-icon"/>#}
    <link rel="stylesheet" href="{% static "app/css/bootstrap.min.css" %}" type="text/css"/>
    <link rel="stylesheet" type="text/css" href="{% static 'app/css/bootstrap-theme.min.css' %}">
    <link rel="stylesheet" href="{% static "app/css/style.css" %}" type="text/css"/>

    <script src="{% static "app/js/jquery.min.js" %}"></script>
</head>
<body>

<header>
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'app:landing' %}">Friend Finder</a>
            </div>
            <ul class="nav navbar-nav">
                {% if user.is_authenticated %}
                    <li><a href="{% url 'app:landing' %}">Home</a></li>
                {% else %}

                {% endif %}
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <p class="navbar-text">{{ user.get_full_name }} ({{ user.username }})</p>
                    <li><a href="{% url 'app:friends' %}">Friends</a></li>
                    <li><a href="{% url 'app:userprofile' %}">My Profile</a></li>
                    <li><a href="{% url 'app:logout' %}">Log Out</a></li>
                {% else %}
                    <li><a href="{% url 'app:login' %}">Log In</a></li>
                    <li><a href="{% url 'app:signup' %}">Sign Up</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>
</header>

<div id="content">
    {% block content %}
    {% endblock %}
</div>

<script type="text/javascript" src="{% static 'app/js/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static 'app/js/bootstrap.min.js' %}"></script>

</body>
</html>

templates/app/friends.html
{% extends "app/base.html" %}

{% load staticfiles %}

{% block content %}
    <div class="container">
    {% if user.is_authenticated %}
        <h3>Friend Manager</h3>

        <section>
            <h4 class="friend-header">Add a Friend</h4>

            <form method="post">
                {% csrf_token %}
                {{ form }}

                <button class="btn btn-primary" type="submit">Add</button>
            </form>
        </section>

        <section>
            <h4 class="friend-header">Requests Sent</h4>
            <ul class="list-group">
                {% for request in requests_sent %}
                    <li class="list-group-item">
                        <a href = "#" class = "list-group-item friend-list-item">
                            <h4 class = "list-group-item-heading">{{ request.to_user.username }}</h4>
                            <p class = "list-group-item-text">{{ request.message }}</p>
                        </a>
                    </li>
                {% endfor %}
            </ul>
        </section>

        <section>
            <h4 class="friend-header">Requests Received</h4>
            <ul class="list-group">
                {% for request in requests_received %}
                    <li class="list-group-item">
                        <h4 class = "list-group-item-heading">{{ request.from_user.username }}</h4>
                        <p class = "list-group-item-text">{{ request.message }}</p>
                        <a href="{% url 'app:manage_friend_requests' operation='accept' pk=request.id %}">
                            <button type="button" class="btn btn-default">Accept</button>
                        </a>
                        <a href="{% url 'app:manage_friend_requests' operation='reject' pk=request.id %}">
                            <button type="button" class="btn btn-default">Reject</button>
                        </a>
                    </li>
                {% endfor %}
            </ul>
        </section>

    {% else %}
            <div class="alert alert-warning">
                <strong>Warning!</strong> You are not logged in.
            </div>
        {% endif %}
    </div>
{% endblock %}

templates/app/landing.html
{% extends "app/base.html" %}

{% load staticfiles %}
{% load leaflet_tags %}

{% block content %}
    <div class="flexbox-container">
        <section>
            <div id="friend-list">
                {% for friend in friends %}
                    <a href = "#" class = "list-group-item friend-list-item"
                        data-id = '{{ friend.id }}'
                        data-username= '{{ friend.username }}'
                        data-firstname= '{{ friend.first_name }}'
                        data-lastname= '{{ friend.last_name }}'
                        data-location= '{{ friend.last_location.geojson }}'
                        data-modified= '{{ friend.modified }}'>
                        <h4 class = "list-group-item-heading">{{ friend.username }}</h4>
                        <p class = "list-group-item-text">{{ friend.modified }}</p>
                    </a>
                {% endfor %}
            </div>
        </section>

        <section>
            <p id="geom">{{ usergeo }}</p>

            <div id="map">

            </div>
        </section>

        <script src="{% static "app/js/map.js" %}"></script>
        <script src="{% static "app/js/resize.js" %}"></script>
    </div>

{% endblock %}

templates/app/login.html
{% extends "app/base.html" %}

{% load staticfiles %}
{% load i18n %}

{% block content %}
    <div class="container">
        <form method="post" action="{% url 'app:login' %}" class="form-signin" role="form">
            {% csrf_token %}
            <h2 class="form-signin-heading">{% trans "Log In" %}</h2>
            {% if form.errors %}
                <div class="alert alert-danger">{% trans "Username or password is incorrect" %}</div>
            {% endif %}

            {% for field in form %}
                {{ field }}
            {% endfor %}

            <button class="btn btn-lg btn-primary btn-block" type="submit">{% trans "Log In" %}</button>
            <br>{% trans "Don't have an account?" %} <a href="{% url 'app:signup' %}">{% trans "Sign up here" %}</a>
        </form>
    </div>
{% endblock %}

templates/app/logout.html
{% extends "app/base.html" %}

{% load staticfiles %}

{% block content %}
    <p>Thank you for visiting. Come back soon.</p>
{% endblock %}

templates/app/signup.html
{% extends "app/base.html" %}

{% load staticfiles %}
{% load i18n %}

{% block content %}
    <div class="container">
        <form method="post" action="." class="form-register" role="form">
            {% csrf_token %}
            <h2 class="form-register-heading">{% trans "Sign up" %}</h2>
                {% if form.errors %}
                    {% for field in form %}
                        {% for error in field.errors %}
                            <div class="alert alert-danger">
                                <strong>Error! </strong>{{ error|escape }}
                            </div>
                        {% endfor %}
                    {% endfor %}
                {% endif %}

                {% for field in form %}
                    {{ field }}
                {% endfor %}

            <button class="btn btn-lg btn-primary btn-block" type="submit">{% trans "Create an account" %}</button>
            <br>{% trans "Do you have an account?" %} <a href="{% url 'app:login' %}">{% trans "Sign in here" %}</a>
        </form>
    </div>

{% endblock %}

templates/app/user_profile.html
{% extends "app/base.html" %}

{% load staticfiles %}
{% load leaflet_tags %}

{% block content %}
    <div class="container">
        {% if user.is_authenticated %}
            <h3>User Profile</h3>

            <form method="post" action="{% url 'app:userprofile' %}" >
                {% csrf_token %}

                {% if form.errors %}
                    {% for field in form %}
                        {% for error in field.errors %}
                            <div class="alert alert-danger">
                                <strong>Error! </strong>{{ error|escape }}
                            </div>
                        {% endfor %}
                    {% endfor %}
                {% endif %}


                {% for field in form %}
                    <div class="form-group row">
                    <label class="col-sm-2 col-form-label">{{ field.label }}</label>
                        <div class="col-xs-3">
                            {{ field }}
                        </div>
                    </div>
                {% endfor %}

                <input type="submit" class="btn btn-primary" value="Save Changes">
            </form>
        {% else %}
            <div class="alert alert-warning">
                <strong>Warning!</strong> You are not logged in.
            </div>
        {% endif %}
    </div>

{% endblock %}